# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-14 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pic',
            field=models.ImageField(default='\templates\x08log\x0cerrari-laferrari-aperta.jpg', height_field=200, max_length=700, upload_to='C:\\Downloads', width_field=300),
        ),
    ]
