# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-14 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pic',
            field=models.ImageField(default='\templates\x08log\x0cerrari-laferrari-aperta.jpg', upload_to='C:\\Downloads'),
        ),
    ]
