# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-14 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170315_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pic',
            field=models.ImageField(default='template/blog/ferrari-laferrari-aperta.jpg', upload_to='C:\\Downloads'),
        ),
    ]
