# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-17 14:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20170317_1938'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='authors',
        ),
    ]
